all :
	@echo "please launch configure before! :"
	@echo "./configure"
	@echo ""
	@echo "then, you can launch:"
	@echo "make"
	@echo "make install"
	@echo ""
	@echo "(see INSTALL file to know how-to-install)"

