//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinHTTrack.rc
//
#define IDC_NewProject                  2
#define IDlog                           3
#define ID_setopt                       3
#define ID_capt                         3
#define IDCANCEL2                       4
#define IDbrowse                        4
#define IDCANCEL3                       5
#define IDD_ABOUTBOX                    100
#define IDD_DIALOGCONTAINER_FORM        106
#define IDR_DIALOGCONTAINER_TMPL        107
#define IDR_MAINFRAME                   128
#define IDR_SHELLTYPE                   129
#define IDD_DIALOG1                     131
#define IDD_DIALOG2                     132
#define IDD_DIALOG3                     133
#define IDD_DIALOG4                     134
#define IDD_DIALOG5                     135
#define IDD_WIZ1                        138
#define IDD_DIALOG6                     141
#define IDD_WIZ2                        142
#define IDD_OPTION                      143
#define IDD_Debut                       147
#define IDD_fin                         148
#define IDD_wizard                      149
#define IDD_fin2                        150
#define IDD_inprogress                  151
#define IDD_wizard_yn                   152
#define IDD_wizard_lnk                  153
#define IDD_ABOUT                       154
#define IDD_AddFilter                   155
#define IDR_MENU1                       158
#define IDR_MENU                        158
#define IDD_iplog                       162
#define IDD_ABOUT_SH                    163
#define IDD_CHOOSEFOLDER                165
#define IDR_POPUP                       167
#define IDD_NewFolder                   168
#define IDD_BuildOptions                172
#define IDR_PROFILE                     175
#define IDC_CURSOR1                     180
#define IDD_ProxyId                     181
#define IDD_NewProj                     182
#define IDD_InsertUrl                   183
#define IDD_OPTION3                     186
#define IDD_OPTION4                     187
#define IDD_OPTION5                     188
#define IDD_OPTION6                     189
#define IDD_OPTION1                     190
#define IDD_OPTION2                     191
#define IDD_OPTION7                     192
#define IDD_OPTION8                     193
#define IDD_OPTION9                     194
#define IDD_OPTION10                    195
#define IDD_HtmlHelp                    197
#define IDB_COLDTOOLBAR                 199
#define IDB_HOTTOOLBAR                  200
#define IDI_BACK                        210
#define IDI_FORWARD                     211
#define IDI_STOP                        212
#define IDI_RELOAD                      213
#define IDB_ENSI                        213
#define IDI_HOME                        214
#define IDD_Wait                        214
#define IDB_ENSI_BACK                   214
#define IDI_PRINT                       215
#define IDD_InfoUrl                     215
#define IDD_CatchUrl                    217
#define IDD_TESTFRAME                   218
#define IDD_TestFrame2                  219
#define IDD_TESTAB                      220
#define IDD_FirstInfo                   221
#define IDR_WINHTTTYPE                  222
#define IDD_OPTION11                    222
#define IDD_BatchUpdate                 223
#define IDR_HELPFRM                     229
#define IDB_SPLASH                      236
#define IDC_CURSWWW                     237
#define IDI_SPLASH                      242
#define IDS_BACK                        748
#define IDS_FORWARD                     749
#define IDS_STOP                        750
#define IDS_REFRESH                     751
#define IDS_HOME                        752
#define IDS_PRINT                       755
#define IDC_URL                         1000
#define IDC_Level                       1001
#define IDC_proxy                       1002
#define IDC_Port                        1003
#define IDC_where1                      1004
#define IDC_where2                      1005
#define IDC_where3                      1006
#define IDC_where4                      1007
#define IDC_RADIO5                      1008
#define IDC_RADIO6                      1009
#define IDC_RADIO7                      1010
#define IDC_RADIO8                      1011
#define IDC_groupwhere                  1012
#define IDC_RADIO1                      1013
#define IDC_scan                        1013
#define IDC_ch1                         1013
#define IDC_logtype                     1013
#define IDC_select_start                1013
#define IDC_RADIO2                      1014
#define IDC_ch2                         1014
#define IDC_select_save                 1014
#define IDC_get                         1015
#define IDC_ch3                         1015
#define IDC_logtype2                    1015
#define IDC_RADIO3                      1016
#define IDC_RADIO4                      1017
#define IDC_EDIT1                       1018
#define IDC_EDIT2                       1019
#define IDC_EDIT3                       1020
#define IDC_CHECK1                      1021
#define IDC_Verbose                     1021
#define IDC_testall                     1021
#define IDC_Freeze                      1021
#define IDC_windebug                    1021
#define IDC_ftpprox                     1021
#define IDC_rasdisc                     1021
#define IDC_inphide                     1021
#define IDC_CHECK2                      1022
#define IDC_log                         1022
#define IDC_link                        1022
#define IDC_ch4                         1022
#define IDC_rasshut                     1022
#define IDC_CHECK3                      1023
#define IDC_Wizard                      1023
#define IDC_pthmir                      1023
#define IDC_ch5                         1023
#define IDC_parseall                    1023
#define IDC_CHECK4                      1024
#define IDC_err                         1024
#define IDC_pathlog                     1024
#define IDC_ch6                         1024
#define IDC_htmlfirst                   1024
#define IDC_CHECK5                      1025
#define IDC_TEST                        1025
#define IDC_index                       1025
#define IDC_projname                    1025
#define IDC_CUSTOM1                     1026
#define IDC_projpath                    1026
#define IDC_XBAR                        1026
#define IDC_index2                      1026
#define IDC_GOUP                        1027
#define IDC_projcateg                   1027
#define IDC_index_mail                  1027
#define IDC_Cache                       1029
#define IDC_dos                         1030
#define IDC_Cache2                      1030
#define IDC_filtre                      1031
#define IDC_remt                        1031
#define IDC_norecatch                   1031
#define IDC_iso9660                     1031
#define IDC_rems                        1032
#define IDC_robots                      1033
#define IDC_ka                          1033
#define IDC_errpage                     1034
#define IDC_external                    1035
#define IDC_prox                        1036
#define IDC_nopurge                     1036
#define IDC_portprox                    1037
#define IDC_hidepwd                     1037
#define IDC_choix2                      1038
#define IDC_proxlogin                   1038
#define IDC_hidequery                   1038
#define IDC_choix3                      1039
#define IDC_proxpass                    1039
#define IDC_URL2                        1040
#define IDC_choix4                      1040
#define IDC_depth                       1040
#define IDC_depth2                      1041
#define IDC_next                        1042
#define IDC_next2                       1043
#define IDC_build                       1045
#define IDC_filter                      1046
#define IDC_travel                      1047
#define IDC_maxhtml                     1048
#define IDC_travel2                     1048
#define IDC_travel3                     1049
#define IDC_sizemax                     1050
#define IDC_connexion                   1051
#define IDC_pausebytes                  1051
#define IDC_timeout                     1052
#define IDC_user                        1053
#define IDC_logf                        1054
#define IDC_footer                      1054
#define IDC_suiv                        1055
#define IDC_rate                        1055
#define IDC_accept_language             1055
#define IDC_niveau                      1056
#define IDC_maxtime                     1056
#define IDC_retry                       1057
#define IDC_maxrate                     1058
#define IDC_COMBO3                      1059
#define IDC_maxconn                     1059
#define IDC_COMBO5                      1060
#define IDC_maxlinks                    1060
#define IDC_Boption                     1061
#define IDC_avant                       1062
#define IDC_ext1                        1062
#define IDC_ext2                        1063
#define IDC_reponse                     1064
#define IDC_question                    1065
#define IDC_othermax                    1066
#define IDC_ext3                        1066
#define IDC_mm                          1067
#define IDC_ext4                        1067
#define IDC_ss                          1068
#define IDC_ext5                        1069
#define IDC_ext6                        1070
#define IDC_ext7                        1071
#define IDC_ext8                        1072
#define IDC_PROGRESS1                   1080
#define IDC_sl0                         1080
#define IDC_RICHEDIT1                   1081
#define IDC_sl1                         1081
#define IDC_PROGRESS2                   1082
#define IDC_sl2                         1082
#define IDC_PROGRESS3                   1083
#define IDC_sl3                         1083
#define IDC_PROGRESS4                   1084
#define IDC_sl4                         1084
#define IDC_PROGRESS5                   1085
#define IDC_sl5                         1085
#define IDC_PROGRESS6                   1086
#define IDC_sl6                         1086
#define IDC_PROGRESS7                   1087
#define IDC_sl7                         1087
#define IDC_PROGRESS8                   1088
#define IDC_sl8                         1088
#define IDC_PROGRESS9                   1089
#define IDC_sl9                         1089
#define IDC_PROGRESS10                  1090
#define IDC_sl10                        1090
#define IDC_PROGRESS11                  1091
#define IDC_sl11                        1091
#define IDC_PROGRESS12                  1092
#define IDC_sl12                        1092
#define IDC_BUTTON1                     1093
#define IDC_sk0                         1093
#define IDC_urls                        1093
#define IDC_ADD2                        1093
#define IDC_BACK                        1093
#define IDC_visit                       1093
#define IDC_CTRL_log                    1093
#define IDC_FIND                        1093
#define IDC_mupdate                     1093
#define IDC_BUTTON2                     1094
#define IDC_sk1                         1094
#define IDC_br1                         1094
#define IDC_ADD1                        1094
#define IDC_FORWARD                     1094
#define IDC_up                          1094
#define IDC_BUTTON3                     1095
#define IDC_sk2                         1095
#define IDC_STOP                        1095
#define IDC_down                        1095
#define IDC_BUTTON4                     1096
#define IDC_sk3                         1096
#define IDC_br2                         1096
#define IDC_RELOAD                      1096
#define IDC_RICHEDIT13                  1097
#define IDC_sk4                         1097
#define IDC_login                       1097
#define IDC_HOME                        1097
#define IDC_RICHEDIT14                  1098
#define IDC_sk5                         1098
#define IDC_PRINT                       1098
#define IDC_RICHEDIT15                  1099
#define IDC_sk6                         1099
#define IDC_login2                      1099
#define IDC_RICHEDIT16                  1100
#define IDC_sk7                         1100
#define IDC_RICHEDIT17                  1101
#define IDC_sk8                         1101
#define IDC_RICHEDIT2                   1102
#define IDC_sk9                         1102
#define IDC_RICHEDIT3                   1103
#define IDC_sk10                        1103
#define IDC_RICHEDIT4                   1104
#define IDC_st0                         1104
#define IDC_st1                         1105
#define IDC_st2                         1106
#define IDC_st3                         1107
#define IDC_i0                          1108
#define IDC_i1                          1109
#define IDC_i2                          1110
#define IDC_st4                         1111
#define IDC_sk11                        1112
#define IDC_sk12                        1113
#define IDC_sk13                        1114
#define IDC_BUTTON5                     1115
#define IDC_STOPALL                     1115
#define IDC_RICHEDIT20                  1116
#define IDC_ipabout                     1116
#define IDC_sl13                        1116
#define IDC_BUTTON6                     1117
#define IDC_st5                         1117
#define IDC_BUTTON7                     1118
#define IDC_st6                         1118
#define IDC_regdef                      1118
#define IDC_BUTTON8                     1119
#define IDC_i3                          1119
#define IDC_BUTTON9                     1120
#define IDC_i4                          1120
#define IDC_BUTTON10                    1121
#define IDC_st7                         1121
#define IDC_BUTTON11                    1122
#define IDC_st8                         1122
#define IDC_BUTTON12                    1123
#define IDC_nm0                         1123
#define IDC_RICHEDIT21                  1124
#define IDC_nm1                         1124
#define IDC_RICHEDIT22                  1125
#define IDC_nm2                         1125
#define IDC_RICHEDIT23                  1126
#define IDC_nm3                         1126
#define IDC_RICHEDIT24                  1127
#define IDC_nm4                         1127
#define IDC_nm5                         1128
#define IDC_nm6                         1129
#define IDC_nm7                         1130
#define IDC_nm8                         1131
#define IDC_nm9                         1132
#define IDC_ttt                         1133
#define IDC_st9                         1133
#define IDskipall                       1134
#define IDC_st10                        1134
#define IDC_hh                          1135
#define IDC_hide                        1135
#define IDC_i5                          1135
#define IDC_proxtitle                   1136
#define IDC_nm10                        1136
#define IDC_st11                        1137
#define IDC_wait                        1138
#define IDC_nm11                        1138
#define IDC_cnx                         1139
#define IDC_st12                        1139
#define IDC_todo                        1140
#define IDC_nm12                        1140
#define IDC_infodepth                   1141
#define IDC_st13                        1141
#define IDC_AFext                       1142
#define IDC_nm13                        1142
#define IDC_AFtype                      1143
#define IDC_i6                          1143
#define IDC_infodepth2                  1143
#define IDC_i7                          1144
#define IDC_nn0                         1146
#define IDC_nn1                         1147
#define IDC_nn2                         1148
#define IDC_nn3                         1149
#define IDC_nn4                         1150
#define IDC_nn5                         1151
#define IDC_nn6                         1152
#define IDC_nn7                         1153
#define IDC_nn8                         1154
#define IDC_nn9                         1155
#define IDC_nn10                        1156
#define IDC_nn11                        1157
#define IDC_mirtitle                    1158
#define IDC_nn12                        1158
#define IDC_infopath                    1159
#define IDC_nn13                        1159
#define IDC_affkeyword                  1160
#define IDC_mirtitle2                   1160
#define IDC_STATIC_updtcontinue         1161
#define IDC_STATIC_basepath             1162
#define IDC_STATIC_updtcontinue2        1163
#define IDC_list                        1169
#define IDC_path                        1170
#define IDC_LIST2                       1171
#define IDC_INFOVER                     1171
#define IDC_INFOMAIN                    1172
#define IDC_inforun                     1173
#define IDC_Folder                      1174
#define IDC_infoend                     1176
#define IDC_lang                        1177
#define IDC_STATIC_action               1178
#define IDC_STATIC_paths                1180
#define IDC_STATIC_thanks               1181
#define IDC_STATIC_filters2             1181
#define IDC_STATIC_support              1182
#define IDC_STATIC_filelist             1182
#define IDC_STATIC_rule                 1183
#define IDC_STATIC_paths2               1183
#define IDC_STATIC_support2             1183
#define IDC_STATIC_m_start              1184
#define IDC_STATIC_delay                1185
#define IDC_STATIC_bytes                1186
#define IDC_STATIC_ras                  1186
#define IDC_STATIC_scanned              1187
#define IDC_STATIC_time                 1188
#define IDC_STATIC_sockets              1189
#define IDC_STATIC_actions              1190
#define IDC_STATIC_type                 1191
#define IDC_STATIC_written              1191
#define IDC_STATIC_buildopt             1192
#define IDC_STATIC_updated              1192
#define IDC_STATIC_primf                1193
#define IDC_STATIC_inprog               1193
#define IDC_STATIC_flowc                1194
#define IDC_STATIC_limits               1195
#define IDC_STATIC_browsid              1196
#define IDC_STATIC_finfo                1197
#define IDC_STATIC_footer               1197
#define IDC_STATIC_tip                  1198
#define IDC_STATIC_accept_language      1198
#define IDC_STATIC_answer               1199
#define IDC_STATIC_other_headers        1199
#define IDC_STATIC_travel               1200
#define IDC_STATIC_default_referer      1200
#define IDC_STATIC_mc                   1201
#define IDC_STATIC_travel2              1201
#define IDC_STATIC_mintr                1202
#define IDC_STATIC_travel3              1202
#define IDC_STATIC_retr                 1203
#define IDC_STATIC_fillim               1204
#define IDC_STATIC_autre                1205
#define IDC_STATIC_sitesize             1206
#define IDC_STATIC_tempmax              1207
#define IDC_STATIC_trate                1208
#define IDC_STATIC_ratemax              1208
#define IDC_buildopt                    1209
#define IDC_STATIC_autre2               1209
#define IDC_STATIC_errors               1209
#define IDC_BuildString                 1210
#define IDC_STATIC_pausebytes           1210
#define IDC_STATIC_maxconn              1211
#define IDC_STATIC_maxlinks             1212
#define IDC_rasid                       1215
#define IDC_changelog                   1217
#define IDC_STATIC_bo1                  1218
#define IDC_STATIC_bo2                  1219
#define IDC_proxadr                     1221
#define IDC_proxport                    1222
#define IDC_STATIC_adr                  1223
#define IDC_STATIC_port                 1224
#define IDC_STATIC_adr2                 1224
#define IDC_STATIC_auth                 1225
#define IDC_STATIC_login                1226
#define IDC_STATIC_pass                 1227
#define IDC_br                          1228
#define IDC_STATIC_capt                 1228
#define IDC_STATIC_projname             1230
#define IDC_STATIC_comments             1231
#define IDC_urlpass                     1232
#define IDC_STATIC_projcateg            1232
#define IDC_urllogin                    1233
#define IDC_urladr                      1234
#define IDC_cookies                     1237
#define IDC_checktype                   1238
#define IDC_parsejava                   1239
#define IDC_proxyconfigure              1239
#define IDC_http10                      1240
#define IDC_toler                       1241
#define IDC_updhack                     1242
#define IDC_urlhack                     1243
#define IDC_STATIC_checktype            1245
#define IDC_HTMLVIEW                    1247
#define IDC_textwait                    1255
#define IDC_STATIC_spider               1256
#define IDC_STATIC_warning              1257
#define IDC_InfoUrl                     1263
#define IDC_slider                      1264
#define IDC_Info100                     1265
#define IDC_MoreInfoUrl                 1266
#define IDC_backlist                    1267
#define IDC_abouticon                   1268
#define IDC_upbar                       1270
#define IDC_info                        1271
#define IDC_STATIC_info                 1272
#define IDC_STATIC_info2                1273
#define IDC_PWDHIDE                     1274
#define IDC_TREE1                       1276
#define ID_StartWiz                     1277
#define IDC_STATIC_webaddr              1279
#define IDC_STATIC_welcome              1280
#define IDC_STATIC_moreinfos            1281
#define ID_BYE                          1282
#define IDC_LIST1                       1283
#define IDC_HIDEINFO                    1284
#define IDC_FINDSTR                     1285
#define IDC_filelist                    1286
#define IDC_STATIC_informations         1288
#define IDC_STATIC_timeout              1290
#define IDC_STATIC_options              1291
#define IDC_STATIC_filetype             1294
#define IDC_STATIC_filetype2            1295
#define IDC_STATIC_mime                 1295
#define IDC_mime1                       1296
#define IDC_STATIC_asso                 1297
#define IDC_mime2                       1298
#define IDC_SPLASH                      1298
#define IDC_mime3                       1299
#define IDC_STATIC_mupdate              1299
#define IDC_mime4                       1302
#define IDC_mime5                       1303
#define IDC_mime6                       1304
#define IDC_mime7                       1305
#define IDC_mime8                       1306
#define IDC_other_headers               1306
#define IDC_default_referer             1308
#define ID_MENUITEM32771                32771
#define ID_MENUITEM32772                32772
#define ID_EXIT                         32772
#define ID_MENUITEM32773                32773
#define ID_MENUITEM32774                32774
#define ID_MENUITEM32775                32775
#define ID_go                           32776
#define ID_QUIT                         32777
#define ID_INFO                         32778
#define ID_VIEW_STOP                    32778
#define ID_OPTSEARCH                    32779
#define ID_VIEW_REFRESH                 32779
#define ID_OPTGET                       32780
#define ID_OPTPAR                       32781
#define ID_VIEW_FONTS_LARGEST           32782
#define ID_VIEW_FONTS_LARGE             32783
#define ID_VIEW_FONTS_MEDIUM            32784
#define ID_VIEW_FONTS_SMALL             32785
#define ID_VIEW_FONTS_SMALLEST          32786
#define ID_GO_BACK                      32787
#define ID_GO_FORWARD                   32788
#define ID_break                        32789
#define ID_GO_START_PAGE                32789
#define ID_GO_SEARCH_THE_WEB            32790
#define ID_GO_BEST_OF_THE_WEB           32791
#define ID_MENUITEM32792                32792
#define ID_FAVORITES_DROPDOWN           32792
#define ID_quithttrack                  32793
#define ID_FONT_DROPDOWN                32793
#define ID_ABOUT                        32794
#define ID_A_ACTIVATE                   32797
#define ID_A_ABOUT                      32798
#define ID_HELP_WEB_TUTORIAL            32798
#define ID_FILE_EXIT                    32799
#define ID_LOG_VIEWLOG                  32800
#define ID_HELP_ONLINE_SUPPORT          32800
#define ID_LOG_VIEWERRORLOG             32801
#define ID_WINDOW_HIDE                  32802
#define ID_FILE_PAUSE                   32803
#define ID_OPTIONS_MODIFYOPTIONS        32805
#define ID_OPTIONS_MODIFY               32805
#define ID_LOAD_OPTIONS                 32808
#define ID_FILE_SAVE_OPTIONS_AS         32809
#define ID_LoadDefaultOptions           32810
#define ID_SaveDefaultOptions           32811
#define IDC_langprefs                   32812
#define ID_NewProjectImport             32813
#define ID_BUTTON_BACK                  32817
#define ID_BUTTON_FORWARD               32818
#define ID_BUTTON_RELOAD                32820
#define ID_BUTTON_HOME                  32821
#define ID_BUTTON_PRINT                 32822
#define ID_BUTTON_STOP                  32823
#define ID_ClearDefaultOptions          32826
#define ID_LOG_VIEWTRANSFERS            32827
#define ID_SaveProject                  32828
#define ID_FILE_WIZARD                  32829
#define ID_FILE_DELETE                  32830
#define ID_FILE_DELETE_PROJ             32831
#define ID_CLOSE                        32832
#define ID_UPDATE                       32833
#define ID_GOWWW                        32834
#define ID_FILE_BROWSE_SIT              32835

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        247
#define _APS_NEXT_COMMAND_VALUE         32837
#define _APS_NEXT_CONTROL_VALUE         1309
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
