.\" Process this file with
.\" groff -man -Tascii webhttrack.1
.\"
.TH webhttrack 1 "Mar 2003" "httrack website copier"
.SH NAME
webhttrack \- offline browser : copy websites to a local directory
.SH SYNOPSIS
.B webhttrack [ keyword value [ keyword value .. ] ]
.B 
.SH DESCRIPTION
.B webhttrack
this program is a script frontend to 
.BR httrack (1)
and
.BR htsserver (1)
, a website copier.
.SH EXAMPLES
.TP
.B webhttrack lang 1
 will launch the webhttrack server frontend, and the default system browser, with "lang" set to "english" (language #1)
.SH FILES
.I /etc/httrack.conf
.RS
The system wide configuration file.
.SH ENVIRONMENT
.IP HOME
Is being used if you defined in /etc/httrack.conf the line
.I path ~/websites/# 
.SH DIAGNOSTICS
Errors/Warnings are reported to 
.I hts-log.txt
located in the destination directory.

.SH BUGS
Please reports bugs to
.B <bugs@httrack.com>.
Include a complete, self-contained example that will allow the bug to be reproduced, and say which version of (web)httrack you are using. Do not forget to detail options used, OS version, and any other information you deem necessary.
.SH COPYRIGHT
Copyright (C) 1998-2013 Xavier Roche and other contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
.SH AVAILABILITY
The  most  recent released version of (web)httrack can be found at:
.B http://www.httrack.com
.SH AUTHOR
Xavier Roche <roche@httrack.com>
.SH "SEE ALSO"
The 
.B HTML 
documentation (available online at
.B http://www.httrack.com/html/
) contains more detailed information. Please also refer to the
.B httrack FAQ
(available online at
.B http://www.httrack.com/html/faq.html
)
