#!/bin/sh
# Assemble HTTrack.app from an installed prefix, then verify it. POSIX sh on purpose: a
# bashism then fails shellcheck, not CI. Payload in Contents/Resources, where webhttrack
# resolves htsserver and its data relative to its own path.
set -eu

usage() {
    echo "usage: $0 --prefix DIR --plist FILE --icon FILE [--out DIR]" >&2
    exit 2
}

prefix=""
plist=""
icon=""
out="."
while [ $# -gt 0 ]; do
    case "$1" in
    --prefix)
        prefix="${2:?}"
        shift 2
        ;;
    --plist)
        plist="${2:?}"
        shift 2
        ;;
    --icon)
        icon="${2:?}"
        shift 2
        ;;
    --out)
        out="${2:?}"
        shift 2
        ;;
    *) usage ;;
    esac
done
test -n "$prefix" || usage
test -n "$plist" || usage
test -n "$icon" || usage
test -r "$prefix/bin/webhttrack" || {
    echo "no webhttrack under $prefix -- run make install first" >&2
    exit 1
}
test -r "$plist" || {
    echo "no Info.plist at $plist -- it is generated by configure" >&2
    exit 1
}
test -r "$icon" || {
    echo "no icon at $icon" >&2
    exit 1
}

prefix=$(cd "$prefix" && pwd -P)
list=$(mktemp)
trap 'rm -f "$list"' EXIT
app="$out/HTTrack.app"
rm -rf "$app"
mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
cp "$plist" "$app/Contents/Info.plist"
cp "$icon" "$app/Contents/Resources/$(basename "$icon")"
cp -R "$prefix"/. "$app/Contents/Resources/"
rm -rf "$app/Contents/Resources/include"
find "$app/Contents/Resources" \( -name '*.la' -o -name '*.a' \) -delete

# webhttrack carries the configure-time datadir as a --datadir fallback (#887);
# in a bundle that is only a build-machine path, and the relative entries ahead
# of it already find the payload.
wht="$app/Contents/Resources/bin/webhttrack"
sed -e "s| \"$prefix/[^\"]*\"||g" "$wht" >"$wht.tmp"
mv -f "$wht.tmp" "$wht"
chmod +x "$wht"

cat >"$app/Contents/MacOS/HTTrack" <<'EOF'
#!/bin/sh
exec "$(dirname "$0")/../Resources/bin/webhttrack" "$@"
EOF
chmod +x "$app/Contents/MacOS/HTTrack"

fail() {
    echo "bundle check: $*" >&2
    exit 1
}

appreal=$(cd "$app" && pwd -P)

find "$app" -type l >"$list"
nlink=0
while IFS= read -r l; do
    nlink=$((nlink + 1))
    case "$(readlink "$l")" in
    /*) fail "absolute symlink $l" ;;
    esac
done <"$list"
test "$nlink" -gt 0 || fail "scanned no symlinks at all, the check proved nothing"

test -d "$app/Contents/Resources/share/httrack/html/server" ||
    fail "Contents/Resources/share/httrack/html/server missing"

# Only our own library must be absent: system and Homebrew dylibs resolve from the
# user's own install.
if command -v otool >/dev/null 2>&1; then
    find "$app/Contents" -type f -perm -u+x >"$list"
    while IFS= read -r bin; do
        file "$bin" | grep -q Mach-O || continue
        if otool -L "$bin" | tail -n +2 | grep -q "$prefix"; then
            otool -L "$bin" >&2
            fail "$bin still links against the staging prefix (build with --disable-shared)"
        fi
    done <"$list"
fi

# otool sees load commands only, so scan the text payload separately. The binaries
# themselves still carry $(datadir) compiled in (#894), so they are not in scope here.
find "$app/Contents" -type f >"$list"
while IFS= read -r f; do
    file "$f" | grep -q text || continue
    grep -q -- "$prefix" "$f" 2>/dev/null && fail "$f embeds the staging prefix"
done <"$list"

# CFBundleIconFile is a Resources basename with an optional extension, so resolve it
# the way Finder does rather than assume the plist and the payload agree.
iconname=$(awk '/<key>CFBundleIconFile<\/key>/ {
        getline; gsub(/^[^>]*>|<[^<]*$/, ""); print; exit }' "$app/Contents/Info.plist")
test -n "$iconname" || fail "Info.plist declares no CFBundleIconFile"
iconfile="$app/Contents/Resources/$iconname"
test -r "$iconfile" || iconfile="$iconfile.icns"
test -r "$iconfile" || fail "CFBundleIconFile names $iconname, absent from Resources"
test "$(head -c 4 "$iconfile")" = icns || fail "$iconfile is not an icns"
# Bytes 4-7 are the container's own length, so a truncated blob fails here rather
# than as a blank icon on someone's Dock.
iconlen=$(od -An -tx1 -j4 -N4 "$iconfile" | tr -d ' \n')
iconsize=$(wc -c <"$iconfile")
test "$((0x$iconlen))" -eq "$iconsize" ||
    fail "$iconfile declares $((0x$iconlen)) bytes but holds $iconsize"

# The plist version is a separate spot from the engine's, so drift is silent unless
# something compares them (#884 is what that looks like when nobody does).
plistver=$(awk '/<key>CFBundleShortVersionString<\/key>/ {
        getline; gsub(/^[^>]*>|<[^<]*$/, ""); print; exit }' "$app/Contents/Info.plist")
binver=$("$app/Contents/Resources/bin/httrack" --version 2>/dev/null |
    sed -n 's/.*[Vv]ersion \([0-9][0-9.]*[-.][0-9][0-9]*\).*/\1/p' | head -1 | tr '-' '.')
test -n "$binver" || fail "could not read a version out of the installed httrack"
test "$plistver" = "$binver" ||
    fail "CFBundleShortVersionString says $plistver, httrack says $binver"
bundlever=$(awk '/<key>CFBundleVersion<\/key>/ {
        getline; gsub(/^[^>]*>|<[^<]*$/, ""); print; exit }' "$app/Contents/Info.plist")
test "$bundlever" = "$binver" ||
    fail "CFBundleVersion says $bundlever, httrack says $binver"

echo "built $appreal (version $plistver)"
