#!/bin/bash
# Assemble HTTrack.app from an installed prefix, then verify it. The payload lives in
# Contents/Resources because webhttrack resolves htsserver and its data relative to its
# own path, so the bundle needs no absolute paths of its own.
set -euo pipefail

usage() {
    echo "usage: $0 --prefix DIR --plist FILE [--out DIR]" >&2
    exit 2
}

prefix=""
plist=""
out="."
while [ $# -gt 0 ]; do
    case "$1" in
    --prefix)
        prefix="${2:?}"
        shift 2
        ;;
    --plist)
        plist="${2:?}"
        shift 2
        ;;
    --out)
        out="${2:?}"
        shift 2
        ;;
    *) usage ;;
    esac
done
test -n "$prefix" || usage
test -n "$plist" || usage
test -r "$prefix/bin/webhttrack" || {
    echo "no webhttrack under $prefix -- run make install first" >&2
    exit 1
}
test -r "$plist" || {
    echo "no Info.plist at $plist -- it is generated by configure" >&2
    exit 1
}

app="$out/HTTrack.app"
rm -rf "$app"
mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
cp "$plist" "$app/Contents/Info.plist"
cp -R "$prefix"/. "$app/Contents/Resources/"

cat >"$app/Contents/MacOS/HTTrack" <<'EOF'
#!/bin/sh
exec "$(dirname "$0")/../Resources/bin/webhttrack" "$@"
EOF
chmod +x "$app/Contents/MacOS/HTTrack"

fail() {
    echo "bundle check: $*" >&2
    exit 1
}

appreal=$(cd "$app" && pwd -P)

while IFS= read -r l; do
    case "$(readlink "$l")" in
    /*) fail "absolute symlink $l" ;;
    esac
done < <(find "$app" -type l)

test -d "$app/Contents/Resources/share/httrack/html/server" ||
    fail "Contents/Resources/share/httrack/html/server missing"

# Only our own library must be absent: system and Homebrew dylibs resolve from the
# user's own install.
if command -v otool >/dev/null 2>&1; then
    while IFS= read -r bin; do
        file "$bin" | grep -q Mach-O || continue
        if otool -L "$bin" | tail -n +2 | grep -q "$prefix"; then
            otool -L "$bin" >&2
            fail "$bin still links against the staging prefix (build with --disable-shared)"
        fi
    done < <(find "$app/Contents" -type f -perm -u+x)
fi

# The plist version is a separate spot from the engine's, so drift is silent unless
# something compares them (#884 is what that looks like when nobody does).
plistver=$(awk '/<key>CFBundleShortVersionString<\/key>/ {
        getline; gsub(/^[^>]*>|<[^<]*$/, ""); print; exit }' "$app/Contents/Info.plist")
binver=$("$app/Contents/Resources/bin/httrack" --version 2>/dev/null |
    sed -n 's/.*[Vv]ersion \([0-9][0-9.]*[-.][0-9][0-9]*\).*/\1/p' | head -1 | tr '-' '.')
test -n "$binver" || fail "could not read a version out of the installed httrack"
test "$plistver" = "$binver" ||
    fail "Info.plist says $plistver, httrack says $binver"

echo "built $appreal (version $plistver)"
