#!/bin/sh
# Assemble HTTrack.app from an installed prefix, then verify it. POSIX sh on purpose: a
# bashism then fails shellcheck, not CI. Payload in Contents/Resources, where webhttrack
# resolves htsserver and its data relative to its own path.
set -eu

# shellcheck source=tools/macos-bundle.sh
. "$(dirname "$0")/macos-bundle.sh"

usage() {
    echo "usage: $0 --prefix DIR --plist FILE --icon FILE [--out DIR]" >&2
    exit 2
}

fail() {
    echo "bundle check: $*" >&2
    exit 1
}

prefix=""
plist=""
icon=""
out="."
while [ $# -gt 0 ]; do
    case "$1" in
    --prefix)
        prefix="${2:?}"
        shift 2
        ;;
    --plist)
        plist="${2:?}"
        shift 2
        ;;
    --icon)
        icon="${2:?}"
        shift 2
        ;;
    --out)
        out="${2:?}"
        shift 2
        ;;
    *) usage ;;
    esac
done
test -n "$prefix" || usage
test -n "$plist" || usage
test -n "$icon" || usage
test -r "$prefix/bin/webhttrack" || {
    echo "no webhttrack under $prefix -- run make install first" >&2
    exit 1
}
test -r "$plist" || {
    echo "no Info.plist at $plist -- it is generated by configure" >&2
    exit 1
}
test -r "$icon" || {
    echo "no icon at $icon" >&2
    exit 1
}

prefix=$(cd "$prefix" && pwd -P)
list=$(mktemp)
mach=$(mktemp)
deplist=$(mktemp)
otmp=$(mktemp)
fwmap=$(mktemp)
trap 'rm -f "$list" "$mach" "$deplist" "$otmp" "$fwmap"' EXIT
app="$out/HTTrack.app"
rm -rf "$app"
mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
cp "$plist" "$app/Contents/Info.plist"
cp "$icon" "$app/Contents/Resources/$(basename "$icon")"
cp -R "$prefix"/. "$app/Contents/Resources/"
# Development surface only, and the .pc would carry the staging prefix in with it.
rm -rf "$app/Contents/Resources/include" "$app/Contents/Resources/lib/pkgconfig"
find "$app/Contents/Resources" \( -name '*.la' -o -name '*.a' \) -delete

# webhttrack carries the configure-time datadir as a --datadir fallback (#887);
# in a bundle that is only a build-machine path, and the relative entries ahead
# of it already find the payload.
wht="$app/Contents/Resources/bin/webhttrack"
sed -e "s| \"$prefix/[^\"]*\"||g" "$wht" >"$wht.tmp"
mv -f "$wht.tmp" "$wht"
chmod +x "$wht"

fw="$app/Contents/Frameworks"

# Everything outside macOS itself must travel with the bundle; OpenSSL comes from Homebrew here.
sysdep() {
    case "$1" in
    /usr/lib/* | /System/Library/*) return 0 ;;
    esac
    return 1
}

# Every file, not a prefilter: this list drives the copy, the relink and the audit alike.
machos() {
    machos_into "$app/Contents" "$mach"
}

# Only the indented lines are dependencies; a universal binary heads each slice.
# A dylib's first entry is its own LC_ID_DYLIB, skipped like any satisfied dependency.
deps() {
    otool -L "$1" >"$otmp" || fail "otool -L failed on $1"
    awk '/^[[:space:]]/ {print $1}' "$otmp"
}

# One ../ per component below Contents, so the rpath is depth-correct wherever the loader sits.
uprefix() {
    printf '%s' "${1#"$app/Contents"}" |
        awk -F/ '{for (i = 1; i <= NF; i++) if ($i != "") printf "../"}'
}

# Rewriting needs header slack that only -headerpad_max_install_names leaves behind.
rewrite() {
    install_name_tool "$@" ||
        fail "install_name_tool failed; link with LDFLAGS=-Wl,-headerpad_max_install_names"
}

# Resolves the directory, which is what Homebrew's opt -> Cellar symlink is.
resolved() {
    (cd "$(dirname "$1")" && printf '%s/%s\n' "$(pwd -P)" "$(basename "$1")")
}

# Each pass rescans, so a dylib pulled in by the last pass gets its own deps on the next.
copy_dylibs() {
    mkdir -p "$fw"
    : >"$fwmap"
    while :; do
        machos
        : >"$deplist"
        while IFS= read -r bin; do
            deps "$bin" >>"$deplist"
        done <"$mach"
        sort -u "$deplist" -o "$deplist"
        : >"$list"
        while IFS= read -r dep; do
            case "$dep" in @*) continue ;; esac
            sysdep "$dep" && continue
            test -r "$dep" || fail "$dep is loaded by the bundle but is not readable here"
            base=$(basename "$dep")
            known=$(awk -v b="$base" '$1 == b {print $2}' "$fwmap")
            if [ -n "$known" ]; then
                # Frameworks is flat, so two distinct libraries under one name would
                # clobber; one library reached by two paths is fine.
                test "$(resolved "$known")" = "$(resolved "$dep")" ||
                    fail "$dep and $known are both named $base"
                continue
            fi
            printf '%s\t%s\n' "$base" "$dep" >>"$fwmap"
            printf '%s\n' "$dep" >>"$list"
        done <"$deplist"
        test -s "$list" || break
        while IFS= read -r dep; do
            cp "$dep" "$fw/"
            chmod u+w "$fw/$(basename "$dep")"
        done <"$list"
    done
    rmdir "$fw" 2>/dev/null || true
}

relink() {
    test -d "$fw" || return 0
    machos
    mainexe=$(main_executable "$app")
    while IFS= read -r bin; do
        case "$bin" in
        "$fw"/*) rewrite -id "@rpath/$(basename "$bin")" "$bin" ;;
        esac
        deps "$bin" >"$deplist"
        while IFS= read -r dep; do
            case "$dep" in @*) continue ;; esac
            sysdep "$dep" && continue
            rewrite -change "$dep" "@rpath/$(basename "$dep")" "$bin"
        done <"$deplist"
        rp="@loader_path/$(uprefix "${bin%/*}")Frameworks"
        otool -l "$bin" | awk '/LC_RPATH/ {r = 1} r && $1 == "path" {print $2; r = 0}' >"$deplist"
        command grep -qxF "$rp" "$deplist" || rewrite -add_rpath "$rp" "$bin"
        # install_name_tool invalidates the signature, and arm64 kills an unsigned Mach-O.
        [ "$bin" = "$mainexe" ] && continue
        codesign -f -s - "$bin"
    done <"$mach"
}

# Unconditional: shipping an unchecked bundle is worse than refusing to build one.
for t in cc otool install_name_tool codesign file; do
    command -v "$t" >/dev/null 2>&1 ||
        fail "$t not found -- macOS bundling needs the Xcode command line tools"
done
# After the preflight, and before the walks below have to find it. headerpad,
# because relink() adds an rpath to every Mach-O in the bundle.
launcher="$(dirname "$0")/httrack-launcher.c"
test -r "$launcher" || fail "no launcher source at $launcher"
cc -O2 -Wall -Wextra -Werror -Wl,-headerpad_max_install_names \
    -o "$(main_executable "$app")" "$launcher" ||
    fail "could not build the bundle launcher from $launcher"

copy_dylibs
relink
# Last, so the seal covers every file the two rewrote. Signing the bundle is also
# what signs the main executable, which codesign will not take on its own.
codesign -f -s - "$app"

appreal=$(cd "$app" && pwd -P)

find "$app" -type l >"$list"
nlink=0
while IFS= read -r l; do
    nlink=$((nlink + 1))
    case "$(readlink "$l")" in
    /*) fail "absolute symlink $l" ;;
    esac
done <"$list"
test "$nlink" -gt 0 || fail "scanned no symlinks at all, the check proved nothing"

test -d "$app/Contents/Resources/share/httrack/html/server" ||
    fail "Contents/Resources/share/httrack/html/server missing"

# The panes reach the manual through this link, and cp -R above keeps it relative.
# A target outside Resources would 404 on every machine but this one.
docdir=$(cd "$app/Contents/Resources/share/httrack/html/doc" 2>/dev/null && pwd -P) ||
    fail "Contents/Resources/share/httrack/html/doc does not resolve"
case "$docdir" in
"$appreal"/*) ;;
*) fail "the documentation link escapes the bundle to $docdir" ;;
esac
test -f "$docdir/html/guide.html" || fail "$docdir holds no html/guide.html"

# A downloaded bundle resolves against macOS and itself; neither the staging prefix nor Homebrew is on the user's machine (#901).
nmach=0
machos
while IFS= read -r bin; do
    nmach=$((nmach + 1))
    deps "$bin" >"$deplist"
    while IFS= read -r dep; do
        case "$dep" in
        @rpath/*)
            test -r "$fw/${dep#@rpath/}" ||
                fail "$bin loads $dep, absent from Contents/Frameworks"
            continue
            ;;
        esac
        sysdep "$dep" && continue
        otool -L "$bin" >&2
        case "$dep" in
        "$prefix"/*)
            fail "$bin links against the staging prefix (build with --disable-shared)"
            ;;
        esac
        fail "$bin loads $dep from outside the bundle"
    done <"$deplist"
done <"$mach"
test "$nmach" -gt 0 || fail "scanned no Mach-O files at all, the check proved nothing"

# otool sees load commands only, so scan the text payload separately. The binaries
# themselves still carry $(datadir) compiled in (#894), so they are not in scope here.
find "$app/Contents" -type f >"$list"
while IFS= read -r f; do
    file "$f" | grep -q text || continue
    command grep -q -- "$prefix" "$f" 2>/dev/null && fail "$f embeds the staging prefix"
done <"$list"

# CFBundleIconFile is a Resources basename with an optional extension, so resolve it
# the way Finder does rather than assume the plist and the payload agree.
iconname=$(plist_value "$app/Contents/Info.plist" CFBundleIconFile)
test -n "$iconname" || fail "Info.plist declares no CFBundleIconFile"
iconfile="$app/Contents/Resources/$iconname"
test -r "$iconfile" || iconfile="$iconfile.icns"
test -r "$iconfile" || fail "CFBundleIconFile names $iconname, absent from Resources"
test "$(head -c 4 "$iconfile")" = icns || fail "$iconfile is not an icns"
# Bytes 4-7 are the container's own length, so a truncated blob fails here rather
# than as a blank icon on someone's Dock.
iconlen=$(od -An -tx1 -j4 -N4 "$iconfile" | tr -d ' \n')
iconsize=$(wc -c <"$iconfile")
test "$((0x$iconlen))" -eq "$iconsize" ||
    fail "$iconfile declares $((0x$iconlen)) bytes but holds $iconsize"

# The plist version is a separate spot from the engine's, so drift is silent unless
# something compares them (#884 is what that looks like when nobody does).
plistver=$(plist_value "$app/Contents/Info.plist" CFBundleShortVersionString)
binver=$("$app/Contents/Resources/bin/httrack" --version 2>/dev/null |
    sed -n 's/.*[Vv]ersion \([0-9][0-9.]*[-.][0-9][0-9]*\).*/\1/p' | head -1 | tr '-' '.')
test -n "$binver" || fail "could not read a version out of the installed httrack"
test "$plistver" = "$binver" ||
    fail "CFBundleShortVersionString says $plistver, httrack says $binver"
bundlever=$(plist_value "$app/Contents/Info.plist" CFBundleVersion)
test "$bundlever" = "$binver" ||
    fail "CFBundleVersion says $bundlever, httrack says $binver"
# A bottled dylib's floor can exceed what the plist declares, and Finder only reads the
# plist. The mismatch fails the build rather than being reconciled behind our backs.
minos=$(macho_floor "$mach") || fail "could not read a minimum macOS out of the payload"
test -n "$minos" || fail "no Mach-O in the bundle declares a minimum macOS"
plistmin=$(plist_value "$app/Contents/Info.plist" LSMinimumSystemVersion)
test "$plistmin" = "$minos" ||
    fail "Info.plist declares macOS $plistmin, the payload needs $minos"

echo "built $appreal (version $plistver, macOS $minos and later)"
