#!/bin/bash
#
# Regenerate htsentities.h from the WHATWG named character references.

set -euo pipefail

src=entities.json
url=https://html.spec.whatwg.org/entities.json
dest=htsentities.h

# 64-bit FNV-1a of $1, printed as a C constant. Must match the hash in
# htsencoding.c. The offset basis is stored as its wrapped (signed) bit pattern;
# bash arithmetic is 64-bit two's complement, so the result is bit-exact.
fnv1a() {
    local s=$1 i c h=$((0xcbf29ce484222325))
    for ((i = 0; i < ${#s}; i++)); do
        printf -v c '%d' "'${s:i:1}"
        h=$(((h ^ (c & 0xff)) * 0x100000001b3))
    done
    printf '0x%016xULL' "$h"
}

if [ ! -f "$src" ]; then
    curl -fsS "$url" -o "$src"
fi

# Keep ';'-terminated single-codepoint names; the ~93 multi-codepoint refs can't
# fit decode_entity's single-codepoint return and are skipped (left verbatim).
pairs=$(jq -r '
    to_entries
    | map(select((.key | endswith(";")) and (.value.codepoints | length == 1)))
    | sort_by(.key)
    | .[] | "\(.key | ltrimstr("&") | rtrimstr(";"))\t\(.value.codepoints[0])"' "$src")

cases=""
records=""
while IFS=$'\t' read -r name cp; do
    hash=$(fnv1a "$name")
    cases+="    /* $name */"$'\n'
    cases+="  case $hash:"$'\n'
    cases+="    if (len == ${#name}) {"$'\n'
    cases+="      return $cp;"$'\n'
    cases+="    }"$'\n'
    cases+="    break;"$'\n'
    records+="$hash ${#name}"$'\n'
done <<<"$pairs"

# The hash-only dispatch is correct only while (hash,len) is unique; prove it
# here so no runtime name compare is needed.
dups=$(printf '%s' "$records" | sort | uniq -d || true)
if [ -n "$dups" ]; then
    echo "FATAL: (hash,len) collision; add name verification or change the hash:" >&2
    echo "$dups" >&2
    exit 1
fi

cat >"$dest" <<EOF
/* GENERATED by $0 from the WHATWG named character references
   (${url}). DO NOT EDIT.
   Dispatch keys on a 64-bit FNV-1a hash of the entity name; the generator
   aborts on any (hash,len) collision, so no runtime name compare is needed. */

#include <stdint.h>

static int decode_entity(const uint64_t hash, const size_t len) {
  switch(hash) {
${cases}  }
  /* unknown */
  return -1;
}
EOF

echo "wrote $dest ($(grep -c '^  case ' "$dest") entities)" >&2
